---
- name: play for installing httpd
  hosts: web
  vars:
    dest: /var/www/html/index.html
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: restart firewall
      service:
        name: firewalld
        state: restarted
        enabled: yes
        
  tasks:
    - name: Install the latest version of Apache
      dnf:
        name: httpd
        state: latest

    - name: copy index.html file to managed nodes
      copy:
        src: index.html
        dest: "{{ dest }}"
      notify: restart httpd

    - name: Permanently enable https service, also enable it immediately if possible
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
      notify: restart firewall

